version: '3.3'
services:
    emqx:
        container_name: emqx
        ports:
            - '1883:1883'
            - '8083:8083'
            - '8084:8084'
            - '8883:8883'
            - '18083:18083'
        image: emqx/emqx